RES_PATH = 'res/'
IMG_PATH = 'res/img/'
SETTINGS_PATH = 'res/settings.json'
CMDS_PATH = 'res/commands/commands.json'
CLIPBOARD_PATH = 'res/clipboard/clipboard.json'
CHAT_PATH = 'res/chat/'
STYLES_PATH = 'res/styles.qss'
