# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app/main.py'],
    pathex=[],
    binaries=[],
    datas=[('app/windows', 'windows'), ('app/res', 'res')],
    hiddenimports=['pynput', 'ollama', 'markdown', 'pygments'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'unittest',
        'doctest',
        'pydoc',
        'xml.dom',
        'xmlrpc',

        'pygments.formatters.bbcode',
        'pygments.formatters.img',
        'pygments.formatters.latex',
        'pygments.formatters.other',
        'pygments.formatters.rtf',
        'pygments.formatters.svg',
        'pygments.styles.abap',
        'pygments.styles.algol',
        'pygments.styles.friendly_grayscale',
        'pygments.styles.native',

        'markdown.extensions.abbr',
        'markdown.extensions.admonition',
        'markdown.extensions.footnotes',
        'markdown.extensions.meta',
        'markdown.extensions.nl2br',
        'markdown.extensions.sane_lists',
        'markdown.extensions.smarty',
        'markdown.extensions.tables',
        'markdown.extensions.toc',
        'markdown.extensions.wikilinks',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='windows-helper',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app/res/img/icon.ico'],
)
